### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by drnikko** [UnstableDesign/AdaCAD-UI#99]
The code version at `3c5bbacacc311313500888cb9b592425bf71d8d7` fails to compile with the error:

```
./node_modules/@tensorflow/tfjs-data/dist/dataset.js:21:0-41 - Error: Module not found: Error: Can't resolve 'seedrandom' in '/Users/nikki/Dropbox/work/AdaCAD/node_modules/@tensorflow/tfjs-data/dist'

./node_modules/@tensorflow/tfjs-data/dist/iterators/lazy_iterator.js:21:0-41 - Error: Module not found: Error: Can't resolve 'seedrandom' in '/Users/nikki/Dropbox/work/AdaCAD/node_modules/@tensorflow/tfjs-data/dist/iterators'
```

From here, you can add `"seedrandom": "^3.0.5",` to `package.json` and rerun.  That will throw the following error:

```
Error: node_modules/@tensorflow/tfjs-core/dist/hash_util.d.ts:2:49 - error TS2304: Cannot find name 'Long'.

2 export declare function hexToLong(hex: string): Long;
                                                  ~~~~


Error: node_modules/@tensorflow/tfjs-core/dist/hash_util.d.ts:3:69 - error TS2304: Cannot find name 'Long'.

3 export declare function fingerPrint64(s: Uint8Array, len?: number): Long;
```

Adding long to `package.json` triggers more errors, as does manually adding seedrandom and trying to do other things.

**Comment by Devendork** [comment]
Hi Nikki,

I think there are a few things that were happening here as a result of your install using Angular 14 and my code on Angular 13. I'm working on updating the code base to so my next major push should include updates that should let you install. That also included temporarily disabling the tensor flow integration, as it looks as that code base does have a breaking change that will hopefully be fixed in a future push.
